import { test, expect } from "@playwright/test";
test.use({ baseURL: "http://127.0.0.1:3001", storageState: process.env.QA_STORAGE_STATE });
test.skip(!process.env.QA_STORAGE_STATE, "Use npm run test:e2e:local.");
test("confirmation modals cancel safely, trap focus, restore focus and protect navigation", async ({ page }) => {
  const nativeDialogs: string[] = [];
  page.on("dialog", async (dialog) => { nativeDialogs.push(dialog.type()); await dialog.dismiss(); });
  await page.goto("/admin/proformas");
  await page.getByLabel("Name", { exact: true }).fill("Keep my edits");
  let signOutRequests = 0;
  await page.route("**/api/auth/sign-out", (route) => { signOutRequests++; return route.fulfill({ status: 503, json: { message: "Temporarily unavailable" } }); });
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  const signOut = page.getByRole("dialog", { name: "Sign out without saving?" });
  await expect(signOut.getByRole("button", { name: "Keep editing" })).toBeFocused();
  expect(signOutRequests).toBe(0);
  await signOut.getByRole("button", { name: "Keep editing" }).click();
  await expect(page.getByLabel("Name", { exact: true })).toHaveValue("Keep my edits");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await signOut.getByRole("button", { name: "Sign out without saving", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "Sign-out failed" })).toBeVisible();
  expect(signOutRequests).toBe(1);
  await page.unroute("**/api/auth/sign-out");
  const start = page.getByRole("button", { name: "New proforma", exact: true });
  await start.click();
  const modal = page.getByRole("dialog", { name: "Start a new proforma?" });
  await expect(modal).toBeVisible();
  await expect(modal.getByRole("button", { name: "Cancel" })).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(modal.getByRole("button", { name: "Start new proforma" })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(modal.getByRole("button", { name: "Cancel" })).toBeFocused();
  await page.screenshot({ path: "test-results/modal-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/modal-mobile.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.keyboard.press("Escape");
  await expect(modal).not.toBeVisible();
  await expect(start).toBeFocused();
  await expect(page.getByLabel("Name", { exact: true })).toHaveValue("Keep my edits");
  await start.click();
  await modal.getByRole("button", { name: "Start new proforma" }).click();
  await expect(page.getByLabel("Name", { exact: true })).toHaveValue("");
  await page.getByLabel("Name", { exact: true }).fill("Unsaved again");
  await page.getByRole("link", { name: "Updates & blog", exact: true }).click();
  const leave = page.getByRole("dialog", { name: "Leave without saving?" });
  await leave.getByRole("button", { name: "Cancel" }).click();
  await expect(page).toHaveURL(/\/admin\/proformas$/);
  await page.getByRole("link", { name: "Updates & blog", exact: true }).click();
  await leave.getByRole("button", { name: "Leave page" }).click();
  await expect(page).toHaveURL(/\/admin\/posts$/);
  await page.goto("/admin/catalogue");
  await expect(page.getByRole("status")).toContainText("Catalogue loaded");
  const name = page.getByLabel("Name", { exact: true });
  const previous = await name.inputValue();
  await name.fill("Unsaved product name");
  await page.getByRole("button", { name: "Reload", exact: true }).click();
  const discard = page.getByRole("dialog", { name: "Discard unsaved edits?" });
  await discard.getByRole("button", { name: "Cancel" }).click();
  await expect(name).toHaveValue("Unsaved product name");
  await page.getByRole("button", { name: "Reload", exact: true }).click();
  await discard.getByRole("button", { name: "Discard and reload" }).click();
  await expect(name).toHaveValue(previous);
  await page.getByRole("button", { name: "Remove", exact: true }).click();
  await page.getByRole("dialog", { name: "Remove this item?" }).getByRole("button", { name: "Cancel" }).click();
  await expect(name).toHaveValue(previous);
  expect(nativeDialogs).toEqual([]);
});
