import { test, expect } from "@playwright/test";
import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd());
const baseURL = process.env.QA_BASE_URL ?? "http://127.0.0.1:3001";
test.use({ baseURL, storageState: process.env.QA_STORAGE_STATE });
test.skip(!process.env.QA_STORAGE_STATE, "Run npm run test:e2e:local for isolated authenticated tests.");
test.setTimeout(120000);
test("posts draft, preview, publish, filter, unpublish and delete", async ({ page, request }) => {
  expect((await fetch(`${baseURL}/admin/api/posts`)).status).toBe(401);
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  const slug = "qa-equipment-arrival";
  await page.goto("/admin/posts");
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toHaveText("Posts loaded.");
  await page.getByRole("button", { name: "Add post", exact: true }).click();
  await page.getByLabel("Title", { exact: true }).fill("QA equipment arrival");
  await page.getByText("Share to LinkedIn", { exact: true }).click();
  await expect(page.getByRole("region", { name: "LinkedIn sharing" })).toContainText("Publish this article before sharing it.");
  await expect(page.getByLabel("URL slug")).toHaveCount(0);
  await expect(page.getByText(`/blog/${slug}`, { exact: true })).toBeVisible();
  await page.getByText("Additional details (optional)", { exact: true }).click();
  await page.getByLabel("Post type").selectOption("Upcoming arrival");
  await expect(page.getByRole("region", { name: "Arrival notice" })).toContainText("90 days");
  await page.getByLabel("Highlight until", { exact: true }).fill("2000-01-01");
  await page.getByLabel("Author", { exact: true }).focus();
  await expect(page.getByText("Choose an expiry on or after the display date.", { exact: true })).toBeVisible();
  await page.getByLabel("Highlight until", { exact: true }).fill("2099-12-31");
  await page.getByLabel("Summary", { exact: true }).fill("New equipment announcement.");
  await page.getByLabel(/^Body/).fill('First paragraph.\n\n<script>alert("unsafe")</script>');
  await page.getByLabel("Cover image", { exact: false }).setInputFiles({ name: "test.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=", "base64") });
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Image uploaded");
  const picture = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=", "base64");
  await page.getByLabel("Add gallery images", { exact: true }).setInputFiles([
    { name: "gallery-1.png", mimeType: "image/png", buffer: picture },
    { name: "gallery-2.png", mimeType: "image/png", buffer: picture },
  ]);
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("2 gallery images uploaded");
  await page.getByLabel("Caption 1", { exact: true }).fill("First equipment view");
  await page.getByLabel("Caption 2", { exact: true }).fill("Second equipment view");
  await page.getByRole("button", { name: "Move image 2 earlier", exact: true }).click();
  await expect(page.getByLabel("Caption 1", { exact: true })).toHaveValue("Second equipment view");
  await page.getByRole("button", { name: /^Save (posts|draft|changes)$/, exact: true }).click();
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Saved.");
  // Streaming loading boundaries can send HTTP 200 before notFound renders.
  expect(await (await request.get(`/blog/${slug}`)).text()).toContain("Page not found");
  const draft = await (await request.get("/admin/api/posts")).json();
  const post = draft.posts.find((p: { slug: string }) => p.slug === slug);
  expect(post.arrivalNoticeUntil).toBe("2099-12-31");
  expect((await request.get(post.image)).status()).toBe(404);
  expect(post.gallery).toHaveLength(2);
  expect((await request.get(post.gallery[0].src)).status()).toBe(404);
  expect((await request.put("/admin/api/posts", { headers: { Origin: "https://bad.example" }, data: draft })).status()).toBe(403);
  expect((await request.put("/admin/api/posts", { headers: { Origin: baseURL }, data: { ...draft, etag: "stale" } })).status()).toBe(409);
  await page.getByRole("button", { name: "Preview post" }).click();
  await expect(page.getByRole("article")).toContainText('<script>alert("unsafe")</script>');
  await expect(page.getByRole("region", { name: "Article gallery" }).locator("img")).toHaveCount(2);
  await page.getByRole("button", { name: "Edit post" }).click();
  await page.getByLabel("Title", { exact: true }).fill("QA equipment arrival revised");
  await expect(page.getByText(`/blog/${slug}`, { exact: true })).toBeVisible();
  await page.getByLabel("Title", { exact: true }).fill("QA equipment arrival");
  await page.getByRole("button", { name: "Publish post", exact: true }).click();
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Post published.");
  await page.getByText("Share to LinkedIn", { exact: true }).click();
  const sharing = page.getByRole("region", { name: "LinkedIn sharing" });
  await expect(sharing).toContainText("Local / preview site");
  await expect(sharing.getByRole("button", { name: "Open LinkedIn company page", exact: true })).toBeDisabled();
  await expect(sharing.getByRole("link", { name: /^Download/ })).toHaveCount(3);
  await sharing.getByLabel("LinkedIn post text", { exact: false }).fill("Custom LinkedIn copy only");
  await expect(page.getByLabel("Title", { exact: true })).toHaveValue("QA equipment arrival");
  await page.evaluate(() => Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async () => { throw new Error("Denied"); } } }));
  await sharing.getByRole("button", { name: "Copy post text", exact: true }).click();
  await expect(sharing.getByRole("status")).toContainText("Clipboard access is unavailable");
  await expect(sharing.getByLabel("LinkedIn post text", { exact: false })).toBeFocused();
  await page.screenshot({ path: "test-results/posts-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await sharing.screenshot({ path: "test-results/linkedin-sharing-mobile.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/posts-mobile.png", fullPage: true });
  expect((await request.get(post.image)).status()).toBe(200);
  expect((await request.get(post.gallery[0].src)).status()).toBe(200);
  await page.goto(`/blog/${slug}`);
  await expect(page.getByRole("heading", { name: "QA equipment arrival", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Article gallery" })).toContainText("Second equipment view");
  await expect(page.getByRole("article")).toContainText('<script>alert("unsafe")</script>');
  await expect(page.locator('meta[property="og:type"]')).toHaveAttribute("content", "article");
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute("href", `https://stemedicaet.com/blog/${slug}`);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/blog-article-mobile.png", fullPage: true });
  await page.goto("/blog?kind=Upcoming%20arrival");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/blog-index-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "test-results/blog-index-desktop.png", fullPage: true });
  await expect(page.getByRole("heading", { name: "QA equipment arrival", exact: true })).toBeVisible();
  await page.goto("/blog?kind=Blog");
  await expect(page.getByRole("heading", { name: "QA equipment arrival", exact: true })).toHaveCount(0);
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "QA equipment arrival", exact: true })).toBeVisible();
  await page.goto("/admin/posts");
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toHaveText("Posts loaded.");
  await page.getByRole("button", { name: "Unpublish post", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Unpublish post", exact: true }).click();
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Post unpublished.");
  expect((await request.get(post.gallery[0].src)).status()).toBe(404);
  await page.getByText("Additional details (optional)", { exact: true }).click();
  await page.getByRole("button", { name: "Remove gallery image 2", exact: true }).click();
  await expect(page.getByLabel("Caption 2", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Saved.");
  const reduced = await (await request.get("/admin/api/posts")).json();
  expect(reduced.posts.find((item: { id: string }) => item.id === post.id).gallery).toHaveLength(1);
  expect(await (await request.get(`/blog/${slug}`)).text()).toContain("Page not found");
  await page.getByRole("button", { name: "Remove post", exact: true }).click();
  const modal = page.getByRole("dialog", { name: "Remove this post?" });
  await expect(modal).toBeVisible();
  await expect(modal.getByRole("button", { name: "Cancel", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(modal).not.toBeVisible();
  await expect(page.getByRole("button", { name: "Remove post", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Remove post", exact: true }).click();
  await modal.getByRole("button", { name: "Remove post", exact: true }).click();
  const deletionSaved = page.waitForResponse((response) => response.url().endsWith("/admin/api/posts") && response.request().method() === "PUT");
  await page.getByRole("button", { name: /^Save (posts|draft|changes)$/, exact: true }).click();
  expect((await deletionSaved).ok()).toBe(true);
  await expect(page.getByRole("region", { name: "Save actions" }).getByRole("status")).toContainText("Saved.");
  expect((await (await request.get("/admin/api/posts")).json()).posts.some((p: { slug: string }) => p.slug === slug)).toBe(false);
  expect(errors).toEqual([]);
});
