import { test, expect } from "@playwright/test";
test.use({ baseURL: "http://127.0.0.1:3001", storageState: process.env.QA_STORAGE_STATE });
test.skip(!process.env.QA_STORAGE_STATE, "Use npm run test:e2e:local.");

test("minimal products and posts support draft, publish, unpublish and stable republishing", async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/test/admin/catalogue");
  await expect(page.getByRole("status")).toContainText("Catalogue loaded");
  await page.getByRole("button", { name: "Add product", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Minimal workflow monitor");
  await page.getByLabel("Brand", { exact: true }).fill("Workflow Brand");
  await expect(page.getByLabel("Name", { exact: true })).toHaveAttribute("aria-required", "true");
  await expect(page.getByLabel("Origin", { exact: true })).not.toBeVisible();
  await expect(page.getByLabel("URL slug")).toHaveCount(0);
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved.");
  const url = "/test/products/minimal-workflow-monitor";
  expect((await request.get(url)).status()).toBe(404);
  await page.getByLabel("Name", { exact: true }).fill("Renamed workflow monitor");
  await page.getByRole("button", { name: "Publish product", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Product published.");
  expect((await request.get(url)).status()).toBe(200);
  const publicPage = await page.context().newPage();
  await publicPage.goto(url);
  await expect(publicPage.locator("dl").first().locator("dt").filter({ hasText: /^Origin$/ })).toHaveCount(0);
  await expect(publicPage.getByText("Placeholder data", { exact: true })).toHaveCount(0);
  await publicPage.close();
  const sidebar = page.getByRole("complementary").first();
  await page.getByRole("button", { name: "Drafts", exact: true }).click();
  await expect(sidebar.getByRole("button", { name: /Renamed workflow monitor/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Published", exact: true }).click();
  await expect(sidebar.getByRole("button", { name: /Renamed workflow monitor/ })).toHaveCount(1);
  await page.getByRole("button", { name: "Unpublish product", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Cancel", exact: true }).click();
  expect((await request.get(url)).status()).toBe(200);
  await page.getByRole("button", { name: "Unpublish product", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Unpublish product", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Product unpublished.");
  expect((await request.get(url)).status()).toBe(404);
  const catalogue = await (await request.get("/test/admin/api/catalogue")).json();
  expect(catalogue.catalogue.products.find((p: { slug: string }) => p.slug === "minimal-workflow-monitor")).toMatchObject({ published: false, brand: "Workflow Brand", category: "", origin: "", summary: "" });
  await page.getByRole("button", { name: "Publish product", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Product published.");
  expect((await request.get(url)).status()).toBe(200);
  await page.screenshot({ path: "test-results/publication-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Add product", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Renamed workflow monitor");
  await page.getByLabel("Brand", { exact: true }).fill("Workflow Brand");
  await expect(page.getByText(/Possible duplicate:/)).toBeVisible();
  await page.getByRole("button", { name: "Open existing product", exact: true }).click();
  await expect(page.getByText(/Website address: \/products\/minimal-workflow-monitor/)).toBeVisible();
  await page.getByRole("button", { name: "Reload", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Discard and reload" }).click();
  await page.goto("/test/admin/posts");
  await expect(page.getByRole("status")).toHaveText("Posts loaded.");
  await page.getByRole("button", { name: "Add post", exact: true }).click();
  await page.getByLabel("Title", { exact: true }).fill("Workflow news");
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved.");
  expect((await request.get("/test/blog/workflow-news")).status()).toBe(404);
  await page.getByRole("button", { name: "Publish post", exact: true }).click();
  await expect(page.getByLabel("Body", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("Body", { exact: true }).fill("Our new equipment update is ready.");
  await page.getByRole("button", { name: "Publish post", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Post published.");
  expect((await request.get("/test/blog/workflow-news")).status()).toBe(200);
  await page.getByRole("button", { name: "Unpublish post", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Unpublish post", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Post unpublished.");
  expect((await request.get("/test/blog/workflow-news")).status()).toBe(404);
  await page.getByLabel("Title", { exact: true }).fill("Renamed workflow news");
  await page.getByRole("button", { name: "Publish post", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Post published.");
  expect((await request.get("/test/blog/workflow-news")).status()).toBe(200);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "test-results/publication-desktop.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
