import { test, expect } from "@playwright/test";
test.use({ baseURL: "http://127.0.0.1:3001", storageState: process.env.QA_STORAGE_STATE });
test.skip(!process.env.QA_STORAGE_STATE, "Use npm run test:e2e:local.");

test("save actions stay reachable, support shortcuts and preserve edits on failure", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/admin/proformas");
  await page.getByLabel("Name", { exact: true }).fill("Save bar test hospital");
  await page.getByLabel("Notes", { exact: true }).fill("Keep these edits after a failed save.");
  const bar = page.getByRole("region", { name: "Save actions" });
  await expect(bar).toContainText("Unsaved changes");
  const box = await bar.boundingBox();
  expect(box!.y).toBeGreaterThan(0);
  expect(box!.y + box!.height).toBeLessThanOrEqual(845);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.route("**/admin/api/drafts", (route) => route.fulfill({ status: 503, json: { error: "Save temporarily unavailable. Please retry." } }));
  await page.keyboard.press("Control+s");
  await expect(bar.getByRole("alert")).toContainText("Save temporarily unavailable");
  await expect(page.getByLabel("Notes", { exact: true })).toHaveValue("Keep these edits after a failed save.");
  await expect(bar.getByRole("button", { name: "Save as draft", exact: true })).toBeEnabled();
  let blockedSaveRequests = 0;
  page.on("request", (request) => { if (request.url().endsWith("/admin/api/drafts") && request.method() === "PUT") blockedSaveRequests++; });
  await page.getByRole("button", { name: "New proforma", exact: true }).click();
  const modal = page.getByRole("dialog", { name: "Start a new proforma?" });
  await page.keyboard.press("Control+s");
  await expect(modal).toBeVisible();
  await modal.getByRole("button", { name: "Cancel", exact: true }).click();
  expect(blockedSaveRequests).toBe(0);
  await page.screenshot({ path: "test-results/save-bar-mobile.png" });
  await page.unroute("**/admin/api/drafts");
  await page.keyboard.press("Control+s");
  await expect(bar.getByRole("status")).toContainText("Draft saved until");
  await expect(bar.getByRole("button", { name: "Save as draft", exact: true })).toBeDisabled();
  await page.getByLabel("Notes", { exact: true }).fill("A new edit after saving");
  await expect(bar).toContainText("Unsaved changes");
  await expect(bar).not.toContainText("Draft saved until");
  await page.keyboard.press("Control+s");
  await expect(bar.getByRole("button", { name: "Save as draft", exact: true })).toBeDisabled();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel("Notes", { exact: true }).scrollIntoViewIfNeeded();
  const desktop = await bar.boundingBox();
  expect(desktop!.y).toBeGreaterThanOrEqual(0);
  expect(desktop!.y).toBeLessThan(50);
  await page.screenshot({ path: "test-results/save-bar-desktop.png" });
  await page.getByRole("button", { name: "Open saved drafts", exact: true }).click();
  const row = page.locator("[data-draft-id]").filter({ hasText: "Save bar test hospital" });
  await expect(row).toHaveCount(1);
  await row.getByRole("button", { name: /^Remove / }).click();
  const removeDialog = page.getByRole("dialog", { name: "Remove saved draft?" });
  await removeDialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(row).toHaveCount(1);
  await row.getByRole("button", { name: /^Remove / }).click();
  await removeDialog.getByRole("button", { name: "Remove draft", exact: true }).click();
  await expect(row).toHaveCount(0);
  await expect(page.getByLabel("Notes", { exact: true })).toHaveValue("A new edit after saving");
  await expect(bar.getByRole("button", { name: "Save as draft", exact: true })).toBeEnabled();
  await page.keyboard.press("Control+s");
  await expect(bar.getByRole("button", { name: "Save as draft", exact: true })).toBeDisabled();
  await page.goto("/admin");
  expect(await page.evaluate(() => document.body.style.paddingBottom)).toBe("");
});
