import { test, expect } from "@playwright/test";
test.use({ baseURL: "http://127.0.0.1:3001", storageState: process.env.QA_STORAGE_STATE });
test.skip(!process.env.QA_STORAGE_STATE, "Use npm run test:e2e:local.");

test("validation identifies fields, navigates between items, and clears corrected errors", async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/admin/catalogue");
  await expect(page.getByRole("status")).toContainText("Catalogue loaded");
  await page.getByRole("button", { name: "Add product", exact: true }).click();
  const name = page.getByLabel("Name", { exact: true });
  await expect(name).not.toHaveAttribute("aria-invalid", "true");
  await name.focus();
  await name.press("Tab");
  await expect(name).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByRole("region", { name: "Fields to check" })).toHaveCount(0);
  await name.fill("Corrected name");
  await expect(name).not.toHaveAttribute("aria-invalid", "true");
  await name.fill("");
  await page.getByRole("button", { name: /^Save (catalogue|draft|changes)$/, exact: true }).click();
  const summary = page.getByRole("region", { name: "Fields to check" });
  await expect(summary).toContainText("Please complete this field.");
  await expect(page.getByLabel("Brand", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByRole("status")).not.toContainText("catalogue.products");
  await expect(page.locator("body")).not.toContainText("must match pattern");
  const brandIssue = summary.getByRole("button", { name: /Brand:/ }).first();
  await brandIssue.click();
  await expect(page.getByLabel("Brand", { exact: true })).toBeFocused();
  await page.getByLabel("Brand", { exact: true }).fill("New brand");
  await expect(page.getByLabel("Brand", { exact: true })).not.toHaveAttribute("aria-invalid", "true");
  await expect(summary.getByRole("button", { name: /Brand:/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Add product", exact: true }).click();
  await expect(page.getByLabel("Brand", { exact: true })).not.toHaveAttribute("aria-invalid", "true");
  await page.getByRole("button", { name: /^Save (catalogue|draft|changes)$/, exact: true }).click();
  await summary.getByRole("button", { name: /Name:/ }).first().click();
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("New brand");
  await summary.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/validation-mobile.png" });
  await page.getByRole("button", { name: "Reload", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Discard and reload" }).click();
  await expect(page.getByRole("status")).toContainText("Catalogue loaded");
  const snapshot = await (await request.get("/admin/api/catalogue")).json();
  snapshot.catalogue.products[0].slug = "INVALID ADDRESS";
  const invalid = await request.put("/admin/api/catalogue", { headers: { Origin: "http://127.0.0.1:3001" }, data: snapshot });
  expect(invalid.status()).toBe(400);
  expect((await invalid.json()).error).not.toMatch(/regex|pattern|catalogue\.products/);
  await page.goto("/admin/posts");
  await expect(page.getByRole("status")).toHaveText("Posts loaded.");
  await page.getByRole("button", { name: "Add post", exact: true }).click();
  await page.getByLabel("Title", { exact: true }).fill("");
  await expect(page.getByLabel("Title", { exact: true })).not.toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("Title", { exact: true }).press("Tab");
  await expect(page.getByLabel("Title", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("Title", { exact: true }).fill("An upcoming arrival");
  await expect(page.getByLabel("Title", { exact: true })).not.toHaveAttribute("aria-invalid", "true");
  await page.getByRole("button", { name: "Publish post", exact: true }).click();
  await expect(summary).toContainText("Add the article text before publishing.");
  await summary.getByRole("button", { name: /Body:/ }).click();
  await expect(page.getByLabel("Body", { exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Reload", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Discard and reload" }).click();
  await page.goto("/admin/proformas");
  await page.getByLabel("Qty", { exact: true }).fill("-1");
  await expect(page.getByLabel("Qty", { exact: true })).not.toHaveAttribute("aria-invalid", "true");
  await page.getByLabel("Qty", { exact: true }).press("Tab");
  await expect(page.getByLabel("Qty", { exact: true })).toHaveAttribute("aria-invalid", "true");
  await page.getByRole("button", { name: "Save as draft", exact: true }).click();
  await expect(summary).toContainText("Item 1 · Quantity");
  await expect(summary).toContainText("Enter a number greater than 0.");
  await summary.getByRole("button", { name: /Quantity:/ }).click();
  await expect(page.getByLabel("Qty", { exact: true })).toBeFocused();
  await page.getByLabel("Qty", { exact: true }).fill("1");
  await expect(summary).toHaveCount(0);
  await page.getByRole("button", { name: "Print / PDF", exact: true }).click();
  await expect(page.getByLabel("Name", { exact: true })).toBeFocused();
});
